source 'https://www.rubygems.org'
gem 'cucumber'
gem 'appium_capybara'
gem 'capybara', '~> 2.15', '>= 2.15.1'
gem 'capybara-screenshot'
gem 'selenium-webdriver'
gem 'rails'
gem 'rspec'
gem 'gherkin'
gem 'pry'
